export enum AuthErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  MISING_DATA = 'MISING_DATA',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  GOOGLE_AUTH_FAILED = 'GOOGLE_AUTH_FAILED',
  ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED',
  ACCOUNT_RESTRICTED = 'ACCOUNT_RESTRICTED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}